version: "3"

services:
    api:
        # FastAPI rules
        container_name: lapico_trainee_fastapi_GloboPlay
        command: "uvicorn main:app --host 0.0.0.0 --port $PORT"
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 8000:$PORT
        env_file: .env
        restart: always